import {useEffect} from 'react'
import Head from "next/head";
import { useRouter } from 'next/router'
import Image from "next/image";
import Link from "next/link";
import { useUser, getSession } from '@auth0/nextjs-auth0';
import styles from "../styles/Home.module.css";

export default function Home() {
  const { user, error, isLoading } = useUser();
  /*   const {data} = getSession() */
 
  const router = useRouter()
  
useEffect(()=>{
console.log(user)
},[user])

  return (
    <div >
      <Head>
        <title>La Nueva esperanza App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="container mx-auto py-5 border-b">
          <img
            src="./logo.png"
            alt=""
            width={125}
          />
        </div>
      </header>
      <main>
        <div className="container mx-auto h-screen grid justify-center content-center">
          <div className="text-center">
        <h1 className="font-black mb-5">Welcome!</h1>
        <Link href="/dashboard" ><p className={`${styles.btnIndexPage} btn bg-yellow-300 text-black px-5 py-2 rounded-md test cursor-pointer`}>Login / Register</p></Link>
        {user && <h3 className="my-5 font-black">{user.name}</h3>}
        </div>
        </div>
      </main>
    </div>
  );
}
